### ISSUE TITLE
Execution time is too long

### ISSUE THREAD

**Issue by icemandala** [gamebtc/devicedetector#1]
```go
gt1 := time.Now()
dd, err := NewDeviceDetector("regexes")
elapsed := time.Since(t1)
fmt.Println("App elapsed: ", elapsed)
```

> App elapsed:  122.718286ms

@gamebtc 
Is there any way to optimize this execution time

**Comment by gamebtc** [comment]
All files will be loaded during initialization. Just initialize once and reuse the result
